apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: webhook-mwc
webhooks:
  - name: mutator.kurly.svc
    clientConfig:
      service:
        name: mutator
        namespace: kurly
        path: "/mutate"
      caBundle: {{CA_PEM_BASE64}}
    rules:
      - operations: [ "CREATE", "UPDATE"]
        apiGroups: ["apps"]
        apiVersions: ["v1"]
        resources: ["deployments", "replicasets"]
    admissionReviewVersions: ["v1", "v1beta1"]
    sideEffects: None
    timeoutSeconds: 5
